#!/bin/bash
 
# suppose qemu-system-aarch64 are available on ubuntu
# or run this command : sudo apt install qemu-system-aarch64 to install it

ARCH=$(uname -m) # you can change it to aarch64
WORKSPACE="workspace"

rm -rf $WORKSPACE
mkdir -p  $WORKSPACE
cd $WORKSPACE

REPO_URL="https://autosd.sig.centos.org/AutoSD-9/nightly/sample-images/"

IMAGE_NAME="auto-osbuild-qemu-autosd9-developer-regular-$ARCH-[0-9]+\.[0-9a-f]+\.qcow2\.xz"

# Use curl to fetch the directory listing
REPO_LISTING=$(curl -s "$REPO_URL")
IMAGE=`echo "$REPO_LISTING" | grep -oE "$IMAGE_NAME" | head -n 1`

echo "The image will be downloaded : "
echo $IMAGE

wget $REPO_URL/$IMAGE 

unxz $IMAGE

wget https://raw.githubusercontent.com/ChrisBale11/osbuild/v.0.1/runVM

chmod +x runVM

echo "Setting up the env is completed !" 

sleep 3

. runVM *.qcow2

# # To shutdown the qemu-system-aarch64 run this command : shutdown -h now 

echo "Do you want clean the workspace (y/n) : "
read answer

# Convert the answer to lowercase to handle both 'Y' and 'y'
answer=$(echo "$answer" | tr '[:upper:]' '[:lower:]')

# Check the user's response
if [ "$answer" == "y" ]; then

    echo "Cleaning the workspace..."
    rm -rf ../workspace
    echo "Workspace cleaned."

elif [ "$answer" == "n" ]; then

    echo "Workspace not cleaned."

else

    echo "Invalid input. Please enter 'y' or 'n'."

fi